@startuml
class Product {
    -partA: String
    -partB: String
    -partC: String
    +Product(builder: ProductBuilder)
}

class ProductBuilder {
    +partA(): void
    +partB(): void
    +partC(): void
    +build(): Product
    partA: String
    partB: String
    partC: String
}

ProductBuilder o-- Product

@enduml
