@startuml
interface Product {
    +operation(): void
}

class ConcreteProductA {
    +operation(): void
}

class ConcreteProductB {
    +operation(): void
}

abstract class Creator {
    +factoryMethod(): Product
}

class ConcreteCreatorA {
    +factoryMethod(): Product
}

class ConcreteCreatorB {
    +factoryMethod(): Product
}

Creator <|-- ConcreteCreatorA
Creator <|-- ConcreteCreatorB
Product <|.. ConcreteProductA
Product <|.. ConcreteProductB
Creator o--> Product

@enduml
