@startuml
interface Product {
    +operation(): void
}

class ConcreteProductA {
    +operation(): void
}

class ConcreteProductB {
    +operation(): void
}

class Creator {
    +factoryMethod(): Product
}

Product <|.. ConcreteProductA
Product <|.. ConcreteProductB
Creator o--> Product

@enduml
